// Defining actions.

export const ALL_PRODUCTS_REQUEST= 'ALL_PRODUCTS_REQUEST'

export const ALL_PRODUCTS_SUCESS= 'ALL_PRODUCTS_SUCESS'
export const ALL_PRODUCTS_FAIL= 'ALL_PRODUCTS_FAIL'
export const ALL_PRODUCTS_CLEAR_ERRORS= 'ALL_PRODUCTS_CLEAR_ERRORS'
